sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: ........
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tEGzhJbvApF8uWn6Z9d
    access-key-secret: LuNpefIEdrJLDKt2qy6bhJ0AJXMjLx
    bucket-name: skyimages
  redis:
    host: localhost
    port: 6379
    database: 10
  wechat:
    appid: wx63c8120caf9d991d
    secret: 146bec00b5b0e2a2a5d9e132756c2444